export const FETCH_HOT_TOPIC_LIST = "FETCH_HOT_TOPIC_LIST";
export const FETCH_HOT_TOPIC_LIST_START = "FETCH_HOT_TOPIC_LIST_START";
export const FETCH_HOT_TOPIC_LIST_SUCCESS = "FETCH_HOT_TOPIC_LIST_SUCCESS";
export const FETCH_HOT_TOPIC_LIST_FAIL = "FETCH_HOT_TOPIC_LIST_FAIL";

export const FETCH_REPLY_LIST = "FETCH_REPLY_LIST";
export const FETCH_REPLY_LIST_START = "FETCH_REPLY_LIST_START";
export const FETCH_REPLY_LIST_SUCCESS = "FETCH_REPLY_LIST_SUCCESS";
export const FETCH_REPLY_LIST_FAIL = "FETCH_REPLY_LIST_FAIL";
